// bankdash-angular/src/app/components/toggle/toggle.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-toggle',
  template: `
    <label class="flex items-center gap-4 cursor-pointer">
      <button
        type="button"
        (click)="onToggle()"
        class="shrink-0 relative transition-colors"
        [style.width.px]="60"
        [style.height.px]="30"
        [style.borderRadius.px]="9999"
        [style.background]="value ? '#16dbcc' : '#e0e0e0'"
      >
        <span
          class="absolute rounded-full bg-white transition-all"
          [style.width.px]="22"
          [style.height.px]="22"
          [style.top.px]="4"
          [style.left.px]="value ? 34 : 4"
        ></span>
      </button>
      <span class="text-base text-ink">{{ label }}</span>
    </label>
  `,
})
export class ToggleComponent {
  @Input() value = false;
  @Input() label = '';
  @Output() valueChange = new EventEmitter<boolean>();
  onToggle() {
    this.valueChange.emit(!this.value);
  }
}

// bankdash-vue/src/components/Toggle.vue
<script setup lang="ts">
const props = defineProps<{ modelValue: boolean; label: string }>();
const emit = defineEmits<{ 'update:modelValue': [v: boolean] }>();
const toggle = () => emit('update:modelValue', !props.modelValue);
</script>

<template>
  <label class="flex items-center gap-4 cursor-pointer">
    <button
      type="button"
      @click="toggle"
      class="shrink-0 relative transition-colors"
      :style="{
        width: '60px',
        height: '30px',
        borderRadius: '9999px',
        background: modelValue ? '#16dbcc' : '#e0e0e0',
      }"
    >
      <span
        class="absolute rounded-full bg-white transition-all"
        :style="{
          width: '22px',
          height: '22px',
          top: '4px',
          left: modelValue ? '34px' : '4px',
        }"
      />
    </button>
    <span class="text-base text-ink">{{ label }}</span>
  </label>
</template>
