// bankdash-vue/src/components/BalanceHistory.vue
<script setup lang="ts">
import { Line } from 'vue-chartjs';
import type { ChartData, ChartOptions } from 'chart.js';

const labels = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'];
const values = [200, 380, 740, 280, 580, 230, 650];

const data: ChartData<'line'> = {
  labels,
  datasets: [
    {
      data: values,
      borderColor: '#1814f3',
      borderWidth: 3,
      pointRadius: 0,
      fill: true,
      tension: 0.45,
      backgroundColor: (ctx) => {
        const chart = ctx.chart;
        const { ctx: c, chartArea } = chart;
        if (!chartArea) return 'rgba(45, 96, 255, 0.2)';
        const g = c.createLinearGradient(0, chartArea.top, 0, chartArea.bottom);
        g.addColorStop(0, 'rgba(45, 96, 255, 0.35)');
        g.addColorStop(1, 'rgba(45, 96, 255, 0)');
        return g;
      },
    },
  ],
};

const options: ChartOptions<'line'> = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: { legend: { display: false } },
  scales: {
    x: { grid: { color: '#f3f3f5' }, ticks: { color: '#718ebf', font: { size: 13 } } },
    y: {
      grid: { color: '#f3f3f5' },
      ticks: { color: '#718ebf', font: { size: 13 }, stepSize: 200 },
      max: 800,
      beginAtZero: true,
    },
  },
};
</script>

<template>
  <div>
    <h2 class="text-3xl font-semibold text-ink mb-5">Balance History</h2>
    <div class="bg-white rounded-card p-6 h-[276px]">
      <Line :data="data" :options="options" />
    </div>
  </div>
</template>

// bankdash-dashboard/src/components/BalanceHistory.tsx
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
} from 'recharts';

const data = [
  { month: 'Jul', value: 200 },
  { month: 'Aug', value: 380 },
  { month: 'Sep', value: 740 },
  { month: 'Oct', value: 280 },
  { month: 'Nov', value: 580 },
  { month: 'Dec', value: 230 },
  { month: 'Jan', value: 650 },
];

export default function BalanceHistory() {
  return (
    <div>
      <h2 className="text-3xl font-semibold text-ink mb-5">Balance History</h2>
      <div className="bg-white rounded-card p-6 h-[276px]">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart
            data={data}
            margin={{ top: 10, right: 10, left: -10, bottom: 0 }}
          >
            <defs>
              <linearGradient id="balanceGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#2d60ff" stopOpacity={0.35} />
                <stop offset="100%" stopColor="#2d60ff" stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid stroke="#f3f3f5" />
            <XAxis
              dataKey="month"
              tick={{ fill: '#718ebf', fontSize: 13 }}
              tickLine={false}
              axisLine={false}
              dy={6}
            />
            <YAxis
              tick={{ fill: '#718ebf', fontSize: 13 }}
              tickLine={false}
              axisLine={false}
              ticks={[0, 200, 400, 600, 800]}
              domain={[0, 800]}
            />
            <Tooltip
              contentStyle={{
                borderRadius: 8,
                border: 'none',
                boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
                fontSize: 13,
              }}
            />
            <Area
              type="monotone"
              dataKey="value"
              stroke="#1814f3"
              strokeWidth={3}
              fill="url(#balanceGrad)"
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
