// bankdash-vue/src/components/MyExpense.vue
<script setup lang="ts">
import { Bar } from 'vue-chartjs';
import type { ChartData, ChartOptions } from 'chart.js';

const labels = ['Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'];
const values = [220, 220, 220, 220, 320, 220];
const highlight = labels.map((_, i) => (i === 4 ? '#16dbcc' : '#edf0f7'));

const data: ChartData<'bar'> = {
  labels,
  datasets: [
    {
      data: values,
      backgroundColor: highlight,
      borderRadius: 20,
      barThickness: 28,
    },
  ],
};

const options: ChartOptions<'bar'> = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false },
    tooltip: { enabled: false },
  },
  scales: {
    x: { grid: { display: false }, ticks: { color: '#718ebf', font: { size: 13 } } },
    y: { display: false, max: 380 },
  },
  layout: { padding: { top: 30 } },
};

const labelPlugin = {
  id: 'topLabel',
  afterDatasetsDraw(chart: import('chart.js').Chart) {
    const { ctx, data: d } = chart;
    const meta = chart.getDatasetMeta(0);
    const idx = 4; // Dec
    const bar = meta.data[idx];
    if (!bar) return;
    const value = (d.datasets[0].data[idx] as number) ?? 0;
    if (!value) return;
    ctx.save();
    ctx.fillStyle = '#343c6a';
    ctx.font = '600 16px Inter, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('$12,500', bar.x, bar.y - 8);
    ctx.restore();
  },
};
</script>

<template>
  <div>
    <h2 class="text-3xl font-semibold text-ink mb-5">My Expense</h2>
    <div class="bg-white rounded-card p-6 h-[225px]">
      <Bar :data="data" :options="options" :plugins="[labelPlugin]" />
    </div>
  </div>
</template>

// bankdash-dashboard/src/components/MyExpense.tsx
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  ResponsiveContainer,
} from 'recharts';

const data = [
  { month: 'Aug', value: 220 },
  { month: 'Sep', value: 220 },
  { month: 'Oct', value: 220 },
  { month: 'Nov', value: 220 },
  { month: 'Dec', value: 320, highlight: true, label: '$12,500' },
  { month: 'Jan', value: 220 },
];

function HighlightLabel(props: {
  x?: number; y?: number; width?: number; index?: number;
}) {
  const { x = 0, y = 0, width = 0, index = 0 } = props;
  const d = data[index];
  if (!d?.label) return null;
  return (
    <text
      x={x + width / 2}
      y={y - 14}
      textAnchor="middle"
      fill="#343c6a"
      fontSize="16"
      fontWeight="600"
    >
      {d.label}
    </text>
  );
}

export default function MyExpense() {
  return (
    <div>
      <h2 className="text-3xl font-semibold text-ink mb-5">My Expense</h2>
      <div className="bg-white rounded-card p-6 h-[225px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={data}
            margin={{ top: 25, right: 5, left: 5, bottom: 0 }}
          >
            <XAxis
              dataKey="month"
              tick={{ fill: '#718ebf', fontSize: 13 }}
              tickLine={false}
              axisLine={false}
              dy={6}
            />
            <YAxis hide domain={[0, 360]} />
            <Bar dataKey="value" radius={[20, 20, 20, 20]} barSize={28} label={HighlightLabel}>
              {data.map((entry, idx) => (
                <Cell
                  key={idx}
                  fill={entry.highlight ? '#16dbcc' : '#edf0f7'}
                />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
