// bankdash-vue/src/components/WeeklyActivity.vue
<script setup lang="ts">
import { Bar } from 'vue-chartjs';
import type { ChartData, ChartOptions } from 'chart.js';

const data: ChartData<'bar'> = {
  labels: ['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  datasets: [
    {
      label: 'Deposit',
      data: [230, 110, 250, 360, 240, 230, 320],
      backgroundColor: '#1814f3',
      borderRadius: 30,
      barThickness: 15,
    },
    {
      label: 'Withdraw',
      data: [470, 340, 320, 470, 150, 390, 400],
      backgroundColor: '#16dbcc',
      borderRadius: 30,
      barThickness: 15,
    },
  ],
};

const options: ChartOptions<'bar'> = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: { legend: { display: false } },
  scales: {
    x: { grid: { display: false }, ticks: { color: '#718ebf', font: { size: 13 } } },
    y: {
      grid: { color: '#f3f3f5' },
      ticks: { color: '#718ebf', font: { size: 13 }, stepSize: 100 },
      max: 500,
      beginAtZero: true,
    },
  },
};
</script>

<template>
  <div>
    <h2 class="text-3xl font-semibold text-ink mb-5">Weekly Activity</h2>
    <div class="bg-white rounded-card p-6 h-[322px] relative">
      <div class="absolute right-6 top-6 flex items-center gap-7 text-base text-ink">
        <div class="flex items-center gap-2"><span class="w-[15px] h-[15px] rounded-full bg-brand" />Deposit</div>
        <div class="flex items-center gap-2"><span class="w-[15px] h-[15px] rounded-full bg-brand-teal" />Withdraw</div>
      </div>
      <div class="w-full h-full pt-8">
        <Bar :data="data" :options="options" />
      </div>
    </div>
  </div>
</template>

// bankdash-dashboard/src/components/WeeklyActivity.tsx
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
} from 'recharts';

const data = [
  { day: 'Sat', deposit: 230, withdraw: 470 },
  { day: 'Sun', deposit: 110, withdraw: 340 },
  { day: 'Mon', deposit: 250, withdraw: 320 },
  { day: 'Tue', deposit: 360, withdraw: 470 },
  { day: 'Wed', deposit: 240, withdraw: 150 },
  { day: 'Thu', deposit: 230, withdraw: 390 },
  { day: 'Fri', deposit: 320, withdraw: 400 },
];

function Legend() {
  return (
    <div className="flex items-center gap-7 text-base text-ink">
      <div className="flex items-center gap-2">
        <span className="w-[15px] h-[15px] rounded-full bg-brand" />
        <span>Deposit</span>
      </div>
      <div className="flex items-center gap-2">
        <span className="w-[15px] h-[15px] rounded-full bg-brand-teal" />
        <span>Withdraw</span>
      </div>
    </div>
  );
}

export default function WeeklyActivity() {
  return (
    <div>
      <h2 className="text-3xl font-semibold text-ink mb-5">Weekly Activity</h2>
      <div className="bg-white rounded-card p-6 h-[322px] relative">
        <div className="absolute right-6 top-6">
          <Legend />
        </div>
        <div className="w-full h-full pt-4">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={data}
              barGap={6}
              barCategoryGap={20}
              margin={{ top: 10, right: 10, left: -20, bottom: 0 }}
            >
              <CartesianGrid stroke="#f3f3f5" vertical={false} />
              <XAxis
                dataKey="day"
                tick={{ fill: '#718ebf', fontSize: 13 }}
                tickLine={false}
                axisLine={false}
                dy={6}
              />
              <YAxis
                tick={{ fill: '#718ebf', fontSize: 13 }}
                tickLine={false}
                axisLine={false}
                ticks={[0, 100, 200, 300, 400, 500]}
                domain={[0, 500]}
              />
              <Tooltip
                cursor={{ fill: 'transparent' }}
                contentStyle={{
                  borderRadius: 8,
                  border: 'none',
                  boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
                  fontSize: 13,
                }}
              />
              <Bar
                dataKey="deposit"
                fill="#1814f3"
                radius={[20, 20, 20, 20]}
                barSize={15}
              />
              <Bar
                dataKey="withdraw"
                fill="#16dbcc"
                radius={[20, 20, 20, 20]}
                barSize={15}
              />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
}
